#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commit_msg=$(cat "${1}")
hotfix_msg="A corregir por "

if git branch -a | grep "*" | grep "hotfix"; then
    if [[ "$commit_msg" == *"$hotfix_msg" ]]; then
        exit 0
    else
        echo "Porfavor asigne a alguien para la validación con 'A corregir por '"
        exit 1
    fi
fi
